version: '3.3'
services:
  quality:
    image: sc-registry.fredhutch.org/quality:latest
    networks:
      - sc-swarm-net
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.quality.rule=Host(`quality.fredhutch.org`)"
        - "traefik.http.routers.quality-secured.rule=Host(`quality.fredhutch.org`)"
        - "traefik.http.routers.quality.entrypoints=web,web-secured"
        - "traefik.http.services.quality.loadbalancer.server.port=5000" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.quality.tls=true"

networks:
  sc-swarm-net:
    external: true